server:
  port: 8080
  servlet:
    context-path: /app
debug: false
spring:
  thymeleaf:
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: bookManager
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3308/demo?useSSL=false
      username: root
      password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
logging:
  config=classpath: log4j2.xml
multipart:
  enabled: true